title = "PolargraphDocs"
baseURL = "https://creativetab.github.io/PolargraphDocs"
languageCode = "en-us"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.fr]
    title = "PolargraphDocs"
    weight = 1
    contentDir = "content/fr"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en]
    title = "PolargraphDocs"
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "CreativeTab"
  favicon = ""
  site_logo = ""
  description = "Docs for the CreativePolargraph"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/creativetab"

[[params.stylesheets]]
path = "css/styles.css"

[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'
    disable = false